package org.wrj.haifa.ai.deerflow.agent;

public enum AgentEventType {
    RUN_STARTED,
    TOOL_STARTED,
    TOOL_COMPLETED,
    MODEL_STARTED,
    MODEL_COMPLETED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_CANCELLED,
    // Research mode events
    RESEARCH_PLAN_CREATED,
    RESEARCH_DIMENSION_STARTED,
    RESEARCH_DIMENSION_COMPLETED,
    SOURCE_FOUND,
    SOURCE_FETCHED,
    EVIDENCE_EXTRACTED,
    QUALITY_GATE_STARTED,
    QUALITY_GATE_PASSED,
    QUALITY_GATE_FAILED,
    REPORT_STARTED,
    REPORT_COMPLETED,
    ARTIFACT_CREATED,
    SUBAGENT_STARTED,
    SUBAGENT_COMPLETED,
    // Loop events
    MODEL_DELTA,
    TOOL_CALL_REQUESTED,
    RESEARCH_STEP_COMPLETED,
    CONTEXT_COMPRESSED,
    TOOL_OUTPUT_BUDGET_EXCEEDED,
    TODO_CREATED,
    TODO_UPDATED,
    TODO_INCOMPLETE,
    TODO_GATE_BLOCKED,
    CLARIFICATION_REQUIRED,
    CLARIFICATION_ANSWERED,
    RUN_SUSPENDED,
    RUN_RESUMED
}

